export const en = {
  // ── Preferences modal ───────────────────────────────────────────────────────
  "prefs.title": "Welcome to Card Metrics",
  "prefs.sub": "Choose your preferences to personalize your experience.",
  "prefs.lang.label": "Language",
  "prefs.lang.fr": "Français",
  "prefs.lang.en": "English",
  "prefs.market.label": "eBay Market",
  "prefs.market.ca": "eBay Canada",
  "prefs.market.ca.sub": "Prices in CAD",
  "prefs.market.us": "eBay United States",
  "prefs.market.us.sub": "Prices in USD",
  "prefs.confirm": "Continue",

  // ── Hero ────────────────────────────────────────────────────────────────────
  "hero.eyebrow": "CARD METRICS · NHL HOCKEY CARDS",
  "hero.title1": "Which hockey cards",
  "hero.title2": "are actually worth buying?",
  "hero.sub":
    "Find undervalued deals on eBay, score any NHL player out of 10, analyze a listing in seconds, track your portfolio in real time. All free, no sign-up.",
  "hero.sub.bold": "All free, no sign-up.",
  "hero.cta_deals": "Search a player",
  "hero.cta_analyse": "Analyze an eBay listing",
  "hero.trust": "100% free · No account needed · 900+ players analyzed",

  // ── Pillars section ─────────────────────────────────────────────────────────
  "pillars.eyebrow": "WHAT YOU CAN DO",
  "pillars.title": "4 WAYS TO USE\nCARD METRICS.",
  "pillars.sub":
    "No expertise needed. Pick your entry point — each tool is independent and free.",

  // Pillar: Deal Finder
  "pillar.deals.tag": "DEAL FINDER",
  "pillar.deals.title": "Find undervalued deals",
  "pillar.deals.body":
    "Search any NHL player and see all their cards listed on eBay — scored and grouped. Young Guns, Autos, Graded, Canvas: everything organized, everything rated.",
  "pillar.deals.cta": "Search a player",

  // Pillar: Analyse
  "pillar.analyse.tag": "ANALYZE",
  "pillar.analyse.title": "Analyze a listing",
  "pillar.analyse.body":
    "See a card on eBay? Paste the link. Card Metrics checks if the price is fair, finds cheaper alternatives, and gives you a full investment verdict.",
  "pillar.analyse.cta": "Analyze an eBay link",

  // Pillar: Score
  "pillar.score.tag": "SCORE & OPPORTUNITIES",
  "pillar.score.title": "Spot the best players",
  "pillar.score.body":
    "Every NHL player gets a score from 0 to 10 based on 13 factors. The Top 8 market opportunities are updated twice a month.",
  "pillar.score.cta": "See opportunities",

  // Pillar: Portfolio
  "pillar.portfolio.tag": "PORTFOLIO & WATCHLIST",
  "pillar.portfolio.title": "Track your cards",
  "pillar.portfolio.body":
    "Add your purchased cards and see their estimated value in real time via live eBay prices. Watchlist players to never miss a great deal.",
  "pillar.portfolio.cta": "My vault",

  // ── Demo section ─────────────────────────────────────────────────────────────
  "demo.eyebrow": "LIVE EXAMPLE",
  "demo.title.prefix": "Search:",
  "demo.sub": "12 eBay listings found · AI scored each card and tells you what to do",
  "demo.cta": "See all Caufield deals",

  // Verdicts
  "verdict.buy": "BUY",
  "verdict.watch": "WATCH",
  "verdict.pass": "PASS",

  // ── Transparency section ─────────────────────────────────────────────────────
  "transp.eyebrow": "TRANSPARENCY",
  "transp.title": "WHAT CARD METRICS\nIS — AND ISN'T.",
  "transp.sub":
    "No empty promises. Here's exactly how the tool works, its limits, and why it can still help you.",
  "transp.beta.label": "Open Beta",
  "transp.beta.text":
    "Card Metrics is in active development. The AI helps filter market noise, but the final decision is always yours. No guarantee of gains — just a better starting point.",
  "transp.prices.label": "Price source",
  "transp.prices.text":
    "Displayed prices come from active eBay listings (asking prices), not completed sales. It's a useful indicator but not a definitive valuation. Sold comps integration is in progress.",
  "transp.ai.label": "AI engine",
  "transp.ai.text":
    "The Card Metrics Score and verdicts are generated by AI. The model analyzes 13 factors (NHL stats, momentum, age, market, hype and more) — but remains a tool, not a financial advisor.",
  "transp.free.label": "100% free, no account",
  "transp.free.text":
    "No mandatory sign-up, no paywall, no personal data collected. If the product helps you, share it — that's the best way to contribute.",

  // ── Welcome Tour ─────────────────────────────────────────────────────────────
  "tour.step": "Step",
  "tour.of": "/",
  "tour.next": "Next",
  "tour.done": "Done",
  "tour.skip": "Skip",
  "tour.welcome.title": "Welcome 👋",
  "tour.welcome.body":
    "Card Metrics tells you which NHL hockey card is actually worth its price — by analyzing eBay listings for you.",
  "tour.analyse.title": "Paste an eBay link",
  "tour.analyse.body":
    "Spotted a card on eBay? Paste the link and get a clear verdict — Buy, Watch, or Pass — in seconds.",
  "tour.deals.title": "Or search a player",
  "tour.deals.body":
    "Type any NHL player's name to see their best cards right now, with AI scores and market rates.",

  // ── Deal Finder ─────────────────────────────────────────────────────────────
  "deals.suggested.label": "Try:",
  "deals.scored.justNow": "Just now",
  "deals.scored.ago": "Scored {min} min ago",
  "deals.refresh": "Refresh",
  "deals.confidence.high": "High confidence — {n} comparables",
  "deals.confidence.medium": "Medium confidence — {n} comparables",
  "deals.confidence.low": "Low confidence — {n} comparables",
  "deals.confidence.indicative": "Indicative — few comparables",
  "deals.confidence.insufficient": "Not enough data",
  "deals.recent.label": "Recent:",
  "deals.recent.remove": "Remove",
  "deals.comps.title": "Recent sales (130point, last 120 days)",
  "deals.comps.date": "Date",
  "deals.comps.price": "Price",
};
